export const LOGAR = 'LOGAR'; // LOGAR NA APLICAÇÃO
export const CADASTRAR_USUARIO = 'CADASTRAR_USUARIO'; // CADASTRO DE USUARIO
export const PESQUISAR = 'PESQUISAR'; // PESQUISAR POR UM VEICULO DIGITANDO A PLACA
